

name: Build and Test integration tests

on:
  push:
    branches: [ "staging" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build integration tests
      run: dotnet build --no-restore
    - name: Test integration tests
      run: dotnet test Homes.IntegrationTests/Homes.IntegrationTests.csproj --verbosity normal
