name: .NET Build and Test

on:
  push:
    branches: [develop, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --configuration Release

      - name: Test Unit Tests (develop branch)
        if: github.ref == 'refs/heads/develop' #conditional run
        run: dotnet test --filter "Category=Unit"

      - name: Test Integration Tests (staging branch)
        if: github.ref == 'refs/heads/staging' #conditional run
        run: dotnet test --filter "Category=Integration"
