name: .NET pipeline for Exam Prep 2

on:
  push:
    branches: [ "develop", "staging" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit tests
      if: github.ref == 'refs/heads/develop'
      run: dotnet test Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal
    - name: Integration tests
      if: github.ref == 'refs/heads/staging'
      run: dotnet test Homes.IntegrationTests/Homes.IntegrationTests.csproj --no-build --verbosity normal
