name: Build the application and run the integration tests

on:
  push:
    branches: [ "staging" ]
jobs:
  build_and_integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET v.6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the application
      run: dotnet build --no-restore
    - name: Run the integration tests
      run: dotnet test Homes.IntegrationTests/Homes.IntegrationTests.csproj --no-build --verbosity normal
