name: Build and run unit tests
on:
  push:
    branches: [ "develop" ]
jobs:
  build_unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET 6 version
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal
