

name: Build and test unit tests

on:
  push:
    branches: [ "develop" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build unit test
      run: dotnet build --no-restore
    - name: Test unit
      run: dotnet test Homies.UnitTests/Homies.UnitTests.csproj --verbosity normal
