# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Running Unit Tests

on:
  push:
    branches: [ "develop" ]
    
jobs:
  BuildAndRunTests:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build the applicaiton 
      run: dotnet build --no-restore

    - name: Run the Unit Tests
      run: dotnet test Homies.UnitTests --no-build --verbosity normal
