name: Build and start unit test

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code 
      uses: actions/checkout@v4
    - name: Setup .NET version 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Execute the unit tests
      run: dotnet test C:/Users/user/Desktop/exam 2/SUContent-SEDO-Regular-Exam-2024-10-2/Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal
