name: Build and run unit tests on develop branch

on:
  push:
    branches: [ "develop" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckOut 
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test Homies.UnitTests.csproj --no-build --verbosity normal
