name: Build and Test .NET App

on:
  push:
    branches:
      - develop
      - staging

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --no-restore

      - name: Run Tests
        run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            dotnet test --filter Category=UnitTests --logger trx --results-directory TestResults/
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            dotnet test --filter Category=IntegrationTests --logger trx --results-directory TestResults/
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults/
